### ISSUE TITLE
Presentation by Vietnamese PhD student.

### ISSUE THREAD

**Issue by RonaldGeskus** [tuyenhn/mathmod-biostats-lab-meeting#1]
Minh Hanh Nguyen is a PhD student in belgium. I met het at a conference last year. She did some interesting work on spatiotemporal spread of SARS-CoV-2 in belgium, and she is more than happy to present this to us. Tuyen, please arrange this with her. 

This is her last email to me:
It'd be an honor to present and discuss our analyses with the OUCRU team. I'd suggest Trang Nguyen (in cc) join as well. She's the co-first author and has worked extensively with spatio-temporal modeling.
Her email is" 
Minh Hanh NGUYEN <minhhanh.nguyen@uhasselt.be>
and Trang's is: Trang NGUYEN <thihuyentrang.nguyen@uhasselt.be>

Ronald

**Comment by tuyenhn** [comment]
Noted. I will be in contact with her to arrange a time and date.
